//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTC.Host.IComun.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MTC.Host.IComun.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El archivo de configuracion {0} no se encontro.
        /// </summary>
        internal static string archivoConfiguracionNoExiste {
            get {
                return ResourceManager.GetString("archivoConfiguracionNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se produjo un error al intentar interrogar por el estado del servicio..
        /// </summary>
        internal static string errorInterrogandoEstadoServicio {
            get {
                return ResourceManager.GetString("errorInterrogandoEstadoServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a secuencia de llamada al metodo Instance invalida. Debe llamarse primero al metodo Instance con el parametro de ensamblado.
        /// </summary>
        internal static string informacionEnsambladoSecuenciaLlamadoInvalida {
            get {
                return ResourceManager.GetString("informacionEnsambladoSecuenciaLlamadoInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontro el target &apos;{0}&apos;.
        /// </summary>
        internal static string logMaganerNoSeEncontroTarget {
            get {
                return ResourceManager.GetString("logMaganerNoSeEncontroTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LogManager no contiene un archivo de configuracion o no existen targets con nombre.
        /// </summary>
        internal static string logManagerNoContieneTarget {
            get {
                return ResourceManager.GetString("logManagerNoContieneTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo encontrar el FileTarget de &apos;{0}&apos;.
        /// </summary>
        internal static string logManagerNoSeEncontroFileTarget {
            get {
                return ResourceManager.GetString("logManagerNoSeEncontroFileTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo conectar al service control manager..
        /// </summary>
        internal static string noSePudoConectarControlManager {
            get {
                return ResourceManager.GetString("noSePudoConectarControlManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servicio no se encuentra instalado..
        /// </summary>
        internal static string servicioNoInstalado {
            get {
                return ResourceManager.GetString("servicioNoInstalado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servicio no pudo ser abierto.
        /// </summary>
        internal static string servicioNoPudoSerAbierto {
            get {
                return ResourceManager.GetString("servicioNoPudoSerAbierto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servicio no pudo ser eliminado: {0}.
        /// </summary>
        internal static string servicioNoPudoSerEliminado {
            get {
                return ResourceManager.GetString("servicioNoPudoSerEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servicio no pudo ser instalado.
        /// </summary>
        internal static string servicioNoPudoSerInstalado {
            get {
                return ResourceManager.GetString("servicioNoPudoSerInstalado", resourceCulture);
            }
        }
    }
}
