//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTC.Nucleo.DucDNS.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MTC.Nucleo.DucDNS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1_1_1_64 {
            get {
                object obj = ResourceManager.GetObject("1-1-1-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abrir la carpeta contenedora.
        /// </summary>
        internal static string abrirCarpetaContenedora {
            get {
                return ResourceManager.GetString("abrirCarpetaContenedora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acerca de.
        /// </summary>
        internal static string acercaDe {
            get {
                return ResourceManager.GetString("acercaDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar.
        /// </summary>
        internal static string actualizar {
            get {
                return ResourceManager.GetString("actualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar ahora.
        /// </summary>
        internal static string actualizarAhora {
            get {
                return ResourceManager.GetString("actualizarAhora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        internal static string agregar {
            get {
                return ResourceManager.GetString("agregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplicacion.
        /// </summary>
        internal static string aplicacion {
            get {
                return ResourceManager.GetString("aplicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe un archivo de auditoria del tipo especificado.
        /// </summary>
        internal static string archivoAuditoriaNoExiste {
            get {
                return ResourceManager.GetString("archivoAuditoriaNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El archivo de configuracion {0} no se encontro.
        /// </summary>
        internal static string archivoConfiguracionNoExiste {
            get {
                return ResourceManager.GetString("archivoConfiguracionNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Signos convencionales:
        ///  ! Arreglo relacionado a seguridad o a algo critico.
        ///  + Nueva caracteristica o arreglo importante.
        ///  - Correccion de errores
        ///
        ///  Prefijos de plataforma:
        ///    MSW: Microsoft Windows
        ///    *nix: Unix (Ej: BSD) y sistemas basados en Unix (Ej. Linux)
        ///    OS X: Apple Mac OS X
        ///
        ///1.0.0.1 (2016-12-14)
        ///- MSW: Bug a la hora de guardar el password.
        ///+ MSW: Agregado del archivo de historial de versiones
        ///+ MSW: Notificacion al momento de introducir la contraseña que es incorrecta
        ///+ MSW: Notificacion e [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string archivoHistorialVersiones {
            get {
                return ResourceManager.GetString("archivoHistorialVersiones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El archivo &apos;{0}&apos; no existe.
        /// </summary>
        internal static string archivoNoExiste {
            get {
                return ResourceManager.GetString("archivoNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        internal static string bAceptar {
            get {
                return ResourceManager.GetString("bAceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar.
        /// </summary>
        internal static string bCerrar {
            get {
                return ResourceManager.GetString("bCerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        internal static string bGuardar {
            get {
                return ResourceManager.GetString("bGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar y nuevo.
        /// </summary>
        internal static string bGuardarYNuevo {
            get {
                return ResourceManager.GetString("bGuardarYNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar correo de prueba.
        /// </summary>
        internal static string bProbarEmail {
            get {
                return ResourceManager.GetString("bProbarEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambio en la direccion IP correcta.
        /// </summary>
        internal static string cambioCorrectoDireccionIP {
            get {
                return ResourceManager.GetString("cambioCorrectoDireccionIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambio en la direccion IP.
        /// </summary>
        internal static string cambioDireccionIP {
            get {
                return ResourceManager.GetString("cambioDireccionIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Novedades de la nueva version.
        /// </summary>
        internal static string cambiosNuevaVersion {
            get {
                return ResourceManager.GetString("cambiosNuevaVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Https.
        /// </summary>
        internal static string checkHttps {
            get {
                return ResourceManager.GetString("checkHttps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Requiere clave para acceder a la consola.
        /// </summary>
        internal static string checkRequierePassword {
            get {
                return ResourceManager.GetString("checkRequierePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Simple.
        /// </summary>
        internal static string checkSimple {
            get {
                return ResourceManager.GetString("checkSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SSL.
        /// </summary>
        internal static string checkSSL {
            get {
                return ResourceManager.GetString("checkSSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar con detalles.
        /// </summary>
        internal static string checkVerbose {
            get {
                return ResourceManager.GetString("checkVerbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha reestablecido la conexion a internet.
        /// </summary>
        internal static string conexionInternetReestablecida {
            get {
                return ResourceManager.GetString("conexionInternetReestablecida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La configuracion no pudo ser guardada!.
        /// </summary>
        internal static string configGuardadaConErrores {
            get {
                return ResourceManager.GetString("configGuardadaConErrores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La configuracion fue guardada con exito!.
        /// </summary>
        internal static string configGuardadaConExito {
            get {
                return ResourceManager.GetString("configGuardadaConExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configurar.
        /// </summary>
        internal static string configurar {
            get {
                return ResourceManager.GetString("configurar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta seguro que desea reiniciar el servicio &apos;{0}&apos;?.
        /// </summary>
        internal static string confirmeReinicioServicio {
            get {
                return ResourceManager.GetString("confirmeReinicioServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este es un correo de prueba.
        /// </summary>
        internal static string correoDePrueba {
            get {
                return ResourceManager.GetString("correoDePrueba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha intentado enviar un correo de prueba a las direccion(es) especificadas.
        /// </summary>
        internal static string correoDePruebaEnviado {
            get {
                return ResourceManager.GetString("correoDePruebaEnviado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Depuracion.
        /// </summary>
        internal static string depuracion {
            get {
                return ResourceManager.GetString("depuracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detener.
        /// </summary>
        internal static string detener {
            get {
                return ResourceManager.GetString("detener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detener actualizacion.
        /// </summary>
        internal static string detenerActualizacion {
            get {
                return ResourceManager.GetString("detenerActualizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        /// </summary>
        internal static System.Drawing.Icon Detenido {
            get {
                object obj = ResourceManager.GetObject("Detenido", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Direccion ip.
        /// </summary>
        internal static string direccionIP {
            get {
                return ResourceManager.GetString("direccionIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El dominio {0} ya existe en la lista de dominios!.
        /// </summary>
        internal static string dominioYaExiste {
            get {
                return ResourceManager.GetString("dominioYaExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        internal static string editar {
            get {
                return ResourceManager.GetString("editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar dominio.
        /// </summary>
        internal static string editarDominio {
            get {
                return ResourceManager.GetString("editarDominio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        /// </summary>
        internal static System.Drawing.Icon Ejecutando {
            get {
                object obj = ResourceManager.GetObject("Ejecutando", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ejecutando como app.
        /// </summary>
        internal static string ejecutandoComoApp {
            get {
                return ResourceManager.GetString("ejecutandoComoApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eiliminar.
        /// </summary>
        internal static string eliminar {
            get {
                return ResourceManager.GetString("eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error intentando obtener la direccion ip publica: {0}.
        /// </summary>
        internal static string errorBuscandoIpPublica {
            get {
                return ResourceManager.GetString("errorBuscandoIpPublica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña incorrecta.
        /// </summary>
        internal static string errorClaveIncorrecta {
            get {
                return ResourceManager.GetString("errorClaveIncorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en la ejecucion del proceso.
        /// </summary>
        internal static string errorEjecucionProceso {
            get {
                return ResourceManager.GetString("errorEjecucionProceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Errores.
        /// </summary>
        internal static string errores {
            get {
                return ResourceManager.GetString("errores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se produjeron errores al tratar de enviar el correo.
        /// </summary>
        internal static string erroresEnviandoCorreo {
            get {
                return ResourceManager.GetString("erroresEnviandoCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en el intento de actualizar los dominios.
        /// </summary>
        internal static string errorIntentandoActualizarLosDominios {
            get {
                return ResourceManager.GetString("errorIntentandoActualizarLosDominios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error intentando obtener el contenido del archivo: {0}.
        /// </summary>
        internal static string errorIntentandoObtenerContenidoArchivo {
            get {
                return ResourceManager.GetString("errorIntentandoObtenerContenidoArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en el intento de actualizacion de la direccion IP.
        /// </summary>
        internal static string errorIntentoActualizarDominio {
            get {
                return ResourceManager.GetString("errorIntentoActualizarDominio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en el intento de obtener la IP publica.
        /// </summary>
        internal static string errorIntentoObtencionIpPublica {
            get {
                return ResourceManager.GetString("errorIntentoObtencionIpPublica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notificaciones.
        /// </summary>
        internal static string grupoNotificaciones {
            get {
                return ResourceManager.GetString("grupoNotificaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servidor de correo.
        /// </summary>
        internal static string grupoSMTP {
            get {
                return ResourceManager.GetString("grupoSMTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Historial de versiones.
        /// </summary>
        internal static string historialDeVersiones {
            get {
                return ResourceManager.GetString("historialDeVersiones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Haga click con el boton derecho sobre el icono para cambiar la configuracion.
        /// </summary>
        internal static string infoAccesoAConfig {
            get {
                return ResourceManager.GetString("infoAccesoAConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Informacion.
        /// </summary>
        internal static string informacion {
            get {
                return ResourceManager.GetString("informacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a iniciado.
        /// </summary>
        internal static string iniciado {
            get {
                return ResourceManager.GetString("iniciado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciando nucleo &apos;{0}&apos;. Version: {1}. Version host contenedor: {2}..
        /// </summary>
        internal static string iniciandoNucleo {
            get {
                return ResourceManager.GetString("iniciandoNucleo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar actualizacion.
        /// </summary>
        internal static string iniciarActualizacion {
            get {
                return ResourceManager.GetString("iniciarActualizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acerca de.
        /// </summary>
        internal static string itemAcercaDe {
            get {
                return ResourceManager.GetString("itemAcercaDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ayuda.
        /// </summary>
        internal static string itemAyuda {
            get {
                return ResourceManager.GetString("itemAyuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        internal static string itemGuardar {
            get {
                return ResourceManager.GetString("itemGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar y salir.
        /// </summary>
        internal static string itemGuardarYSalir {
            get {
                return ResourceManager.GetString("itemGuardarYSalir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        internal static string itemSalir {
            get {
                return ResourceManager.GetString("itemSalir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sistema.
        /// </summary>
        internal static string itemSistema {
            get {
                return ResourceManager.GetString("itemSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirme.
        /// </summary>
        internal static string K_CONFIRME {
            get {
                return ResourceManager.GetString("K_CONFIRME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizador DucDNS.
        /// </summary>
        internal static string labelActualizadorDucDNS {
            get {
                return ResourceManager.GetString("labelActualizadorDucDNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clave:.
        /// </summary>
        internal static string labelClaveCredenciales {
            get {
                return ResourceManager.GetString("labelClaveCredenciales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clave.
        /// </summary>
        internal static string labelClaveSMTP {
            get {
                return ResourceManager.GetString("labelClaveSMTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string labelColumnaNombre {
            get {
                return ResourceManager.GetString("labelColumnaNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desarrollado por MTCSistemas.
        /// </summary>
        internal static string labelDesarroladoPor {
            get {
                return ResourceManager.GetString("labelDesarroladoPor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripcion de este equipo.
        /// </summary>
        internal static string labelDescripcionEquipo {
            get {
                return ResourceManager.GetString("labelDescripcionEquipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email:.
        /// </summary>
        internal static string labelEmail {
            get {
                return ResourceManager.GetString("labelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Emails a notificar (separados por coma).
        /// </summary>
        internal static string labelEmailsANotificar {
            get {
                return ResourceManager.GetString("labelEmailsANotificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Intervalo act. (minutos):.
        /// </summary>
        internal static string labelIntervaloActualizacionMinutos {
            get {
                return ResourceManager.GetString("labelIntervaloActualizacionMinutos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modo debug:.
        /// </summary>
        internal static string labelModoDebug {
            get {
                return ResourceManager.GetString("labelModoDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre:.
        /// </summary>
        internal static string labelNombreDominio {
            get {
                return ResourceManager.GetString("labelNombreDominio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notificar.
        /// </summary>
        internal static string labelNotificar {
            get {
                return ResourceManager.GetString("labelNotificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puerto:.
        /// </summary>
        internal static string labelPuertoSMTP {
            get {
                return ResourceManager.GetString("labelPuertoSMTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servidor SMTP:.
        /// </summary>
        internal static string labelServidorSMTP {
            get {
                return ResourceManager.GetString("labelServidorSMTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Llave.
        /// </summary>
        internal static string labelToken {
            get {
                return ResourceManager.GetString("labelToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario:.
        /// </summary>
        internal static string labelUsuarioSMTP {
            get {
                return ResourceManager.GetString("labelUsuarioSMTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe conexion a internet.
        /// </summary>
        internal static string noExisteConexionInternet {
            get {
                return ResourceManager.GetString("noExisteConexionInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizacion correcta direccion IP.
        /// </summary>
        internal static string notificaActualizacionCorrectaIP {
            get {
                return ResourceManager.GetString("notificaActualizacionCorrectaIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambio de IP.
        /// </summary>
        internal static string notificaCambioIp {
            get {
                return ResourceManager.GetString("notificaCambioIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Errores en intento de cambio de IP.
        /// </summary>
        internal static string notificaErrorCambioIp {
            get {
                return ResourceManager.GetString("notificaErrorCambioIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Otros errores.
        /// </summary>
        internal static string notificaOtrosErrores {
            get {
                return ResourceManager.GetString("notificaOtrosErrores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perdida de conexion a internet.
        /// </summary>
        internal static string notificaPerdidaConexionInternet {
            get {
                return ResourceManager.GetString("notificaPerdidaConexionInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reestablecimiento de conexion a internet.
        /// </summary>
        internal static string notificaReestablecimientoConexionInternet {
            get {
                return ResourceManager.GetString("notificaReestablecimientoConexionInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nucleo detenido.
        /// </summary>
        internal static string nucleoDetenido {
            get {
                return ResourceManager.GetString("nucleoDetenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nucleo iniciado.
        /// </summary>
        internal static string nucleoIniciado {
            get {
                return ResourceManager.GetString("nucleoIniciado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta disponible una nueva version: {0}.
        /// </summary>
        internal static string nuevaVersionDisponible {
            get {
                return ResourceManager.GetString("nuevaVersionDisponible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo dominio.
        /// </summary>
        internal static string nuevoDominio {
            get {
                return ResourceManager.GetString("nuevoDominio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opciones.
        /// </summary>
        internal static string opciones {
            get {
                return ResourceManager.GetString("opciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta seguro que desea {0} el servicio &apos;{1}&apos;?.
        /// </summary>
        internal static string operacionSobreServicio {
            get {
                return ResourceManager.GetString("operacionSobreServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha perdido la conexion a internet.
        /// </summary>
        internal static string perdidaConexionInternet {
            get {
                return ResourceManager.GetString("perdidaConexionInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proceso de actualizacion.
        /// </summary>
        internal static string procesoActualizacion {
            get {
                return ResourceManager.GetString("procesoActualizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proceso completado con errores.
        /// </summary>
        internal static string procesoCompletadoConErrores {
            get {
                return ResourceManager.GetString("procesoCompletadoConErrores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proceso completado con exito.
        /// </summary>
        internal static string procesoCompletadoConExito {
            get {
                return ResourceManager.GetString("procesoCompletadoConExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La seccion &apos;{0}&apos; no pudo ser encontrada.
        /// </summary>
        internal static string seccionNoEncontrada {
            get {
                return ResourceManager.GetString("seccionNoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se enviaron correos de notificacion a las direcciones.
        /// </summary>
        internal static string seEnviaronNotificacionesADirecciones {
            get {
                return ResourceManager.GetString("seEnviaronNotificacionesADirecciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servicio.
        /// </summary>
        internal static string servicio {
            get {
                return ResourceManager.GetString("servicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desinstalar.
        /// </summary>
        internal static string servicioDesinstalar {
            get {
                return ResourceManager.GetString("servicioDesinstalar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detener y salir.
        /// </summary>
        internal static string servicioDetenerYSalir {
            get {
                return ResourceManager.GetString("servicioDetenerYSalir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a detenido.
        /// </summary>
        internal static string servicioDetenido {
            get {
                return ResourceManager.GetString("servicioDetenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a en ejecucion.
        /// </summary>
        internal static string servicioEnEjecucion {
            get {
                return ResourceManager.GetString("servicioEnEjecucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a estado desconocido.
        /// </summary>
        internal static string servicioEstadoDesconocido {
            get {
                return ResourceManager.GetString("servicioEstadoDesconocido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar.
        /// </summary>
        internal static string servicioIniciar {
            get {
                return ResourceManager.GetString("servicioIniciar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar y salir.
        /// </summary>
        internal static string servicioIniciarYSalir {
            get {
                return ResourceManager.GetString("servicioIniciarYSalir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Instalar.
        /// </summary>
        internal static string servicioInstalar {
            get {
                return ResourceManager.GetString("servicioInstalar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a no instalado.
        /// </summary>
        internal static string servicioNoInstalado {
            get {
                return ResourceManager.GetString("servicioNoInstalado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restart.
        /// </summary>
        internal static string servicioReiniciar {
            get {
                return ResourceManager.GetString("servicioReiniciar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        /// </summary>
        internal static System.Drawing.Icon SinConfigurar {
            get {
                object obj = ResourceManager.GetObject("SinConfigurar", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay dominios que actualizar.
        /// </summary>
        internal static string sinDominiosQueActualizar {
            get {
                return ResourceManager.GetString("sinDominiosQueActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dominios.
        /// </summary>
        internal static string tabDominios {
            get {
                return ResourceManager.GetString("tabDominios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notificaciones.
        /// </summary>
        internal static string tabNotificaciones {
            get {
                return ResourceManager.GetString("tabNotificaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Principal.
        /// </summary>
        internal static string tabPrincipal {
            get {
                return ResourceManager.GetString("tabPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguridad.
        /// </summary>
        internal static string tabSeguridad {
            get {
                return ResourceManager.GetString("tabSeguridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asunto.
        /// </summary>
        internal static string tasunto {
            get {
                return ResourceManager.GetString("tasunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripcion del equipo.
        /// </summary>
        internal static string tdescripcionEquipo {
            get {
                return ResourceManager.GetString("tdescripcionEquipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalles.
        /// </summary>
        internal static string tdetalles {
            get {
                return ResourceManager.GetString("tdetalles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        internal static string tfecha {
            get {
                return ResourceManager.GetString("tfecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha definido el token.
        /// </summary>
        internal static string tokenNoDefinido {
            get {
                return ResourceManager.GetString("tokenNoDefinido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de notificacion.
        /// </summary>
        internal static string ttipoNotificacion {
            get {
                return ResourceManager.GetString("ttipoNotificacion", resourceCulture);
            }
        }
    }
}
